package com.mgm.dmp.dao;

import com.mgmresorts.aurora.messages.*;

public interface AuroraConnectionDAO {
	
	
	
	//Aurora Dining booking dao methods
	GetDiningAvailabilityResponse getDiningAvailability(GetDiningAvailabilityRequest request);
	
	SaveDiningReservationResponse saveDiningReservation(SaveDiningReservationRequest request);
	
	MakeDiningReservationResponse makeDiningReservation(MakeDiningReservationRequest request);
	
	CancelDiningReservationResponse cancelDiningReservation(CancelDiningReservationRequest request);
	
	RemoveDiningReservationResponse removeDiningReservation(RemoveDiningReservationRequest request);
	
	//Aurora Offer dao methods
	
	IsProgramApplicableResponse isProgramApplicable(IsProgramApplicableRequest request);
	
	//Aurora Itinerary dao methods
	
	CreateCustomerItineraryResponse createCustomerItinerary(CreateCustomerItineraryRequest request);
	
	AddCustomerItineraryResponse addCustomerItinerary(AddCustomerItineraryRequest request);
	
	UpdateCustomerItineraryResponse updateCustomerItinerary(UpdateCustomerItineraryRequest request);
	
	GetCustomerItinerariesResponse getCustomerItineraries(GetCustomerItinerariesRequest request);
	
	GetCustomerItineraryByDiningConfirmationNumberResponse getCustomerItineraryByDiningConfirmationNumber(GetCustomerItineraryByDiningConfirmationNumberRequest request);
	
	GetCustomerItineraryByRoomConfirmationNumberResponse getCustomerItineraryByRoomConfirmationNumber(GetCustomerItineraryByRoomConfirmationNumberRequest request);
	
	GetCustomerItineraryByShowConfirmationNumberResponse getCustomerItineraryByShowConfirmationNumber(GetCustomerItineraryByShowConfirmationNumberRequest request);
	
	//Aurora Customer dao methods
	
	GetCustomerByWebCredentialsResponse getCustomerByWebCredentials(GetCustomerByWebCredentialsRequest request);
	
	AddCustomerResponse addCustomer(AddCustomerRequest request);
	
	UpdateCustomerResponse updateCustomer(UpdateCustomerRequest request);
	
	SearchCustomerResponse searchCustomer(SearchCustomerRequest request);
	
	CreateCustomerWebCredentialsResponse createCustomerWebCredentials(CreateCustomerWebCredentialsRequest request);
	
	ActivateCustomerWebCredentialsResponse activateCustomerWebCredentials(ActivateCustomerWebCredentialsRequest request);
	
	ValidateCustomerWebCredentialsResponse validateCustomerWebCredentials(ValidateCustomerWebCredentialsRequest request);
	
	ResetCustomerWebPasswordResponse resetCustomerWebPassword(ResetCustomerWebPasswordRequest request);
	
	ChangeCustomerWebEmailAddressResponse changeCustomerWebEmailAddress(ChangeCustomerWebEmailAddressRequest request);
	
	ChangeCustomerWebPasswordAdminResponse changeCustomerWebPasswordAdmin(ChangeCustomerWebPasswordAdminRequest request);
	
	ChangeCustomerWebSecretQuestionAnswerResponse changeCustomerWebSecretQuestionAnswer(ChangeCustomerWebSecretQuestionAnswerRequest request);
	
	ValidateCustomerWebSecretAnswerResponse validateCustomerWebSecretAnswer(ValidateCustomerWebSecretAnswerRequest request);
	
	GetCustomerBalancesFullResponse getCustomerBalancesFull(GetCustomerBalancesFullRequest request);
	
	GetCustomerTaxInformationResponse getCustomerTaxInformation(GetCustomerTaxInformationRequest request);
	
	SendEmailResponse sendEmail(SendEmailRequest request);
	
	GetCustomerGuestBookPreferencesResponse getCustomerGuestBookPreferences(GetCustomerGuestBookPreferencesRequest request);
	
	SetCustomerGuestBookPreferencesResponse setCustomerGuestBookPreferences(SetCustomerGuestBookPreferencesRequest request);
	
	GetCustomerByIdResponse getCustomerById(GetCustomerByIdRequest request);
	
	//Aurora Room booking dao methods
	
	GetRoomPricingAndAvailabilityResponse getRoomPricingAndAvailabilityEx(GetRoomPricingAndAvailabilityExRequest request);
	
	GetProgramByOperaPromoCodeResponse getProgramByOperaPromoCode(GetProgramByOperaPromoCodeRequest request);
	
	GetApplicableProgramsResponse getApplicablePrograms(GetApplicableProgramsRequest request);
	
	GetCustomerOffersResponse getCustomerOffers(GetCustomerOffersRequest request);
	
	UpdateRoomReservationResponse updateRoomReservation(UpdateRoomReservationRequest request);
	
	MakeRoomReservationResponse makeRoomReservation(MakeRoomReservationRequest request);
	
	GetRoomComponentAvailabilityResponse getRoomComponentAvailability(GetRoomComponentAvailabilityRequest request);
	
	RemoveRoomReservationResponse removeRoomReservation(RemoveRoomReservationRequest request);
	
	SaveRoomReservationResponse saveRoomReservation(SaveRoomReservationRequest request);
	
	CancelRoomReservationResponse cancelRoomReservation(CancelRoomReservationRequest request);
	
	//Aurora show booking dao methods
	HoldBestAvailableShowTicketsResponse holdBestAvailableShowTickets(HoldBestAvailableShowTicketsRequest request);
	
	GetShowProgramsByArchticsPromoCodeResponse getShowProgramsByArchticsPromoCode(GetShowProgramsByArchticsPromoCodeRequest request);
	
	GetShowProgramEventsResponse getShowProgramEvents(GetShowProgramEventsRequest request);
	
	GetApplicableShowProgramsResponse getApplicableShowPrograms(GetApplicableShowProgramsRequest request);
	
	GetShowPricingAndAvailabilityResponse getShowPricingAndAvailability(GetShowPricingAndAvailabilityRequest request);
	
	GetShowPricingAndAvailabilityResponse getShowPricingAndAvailabilityByProgram(GetShowPricingAndAvailabilityByProgramRequest request);
	
	HoldSpecificShowTicketsResponse holdSpecificShowTickets(HoldSpecificShowTicketsRequest request);
	
	ReleaseShowTicketsResponse releaseShowTickets(ReleaseShowTicketsRequest request);
	
	SaveShowReservationResponse saveShowReservation(SaveShowReservationRequest request);
	
	RemoveShowReservationResponse removeShowReservation(RemoveShowReservationRequest request);
	
	UpdateShowReservationResponse updateShowReservation(UpdateShowReservationRequest request);
	
	MakeShowReservationResponse makeShowReservation(MakeShowReservationRequest request);
	
	PrintShowTicketsResponse printShowTickets(PrintShowTicketsRequest request);
	
	IsShowProgramApplicableResponse isShowProgramApplicable(IsShowProgramApplicableRequest request);
	
	//General methods
	void closeConnection();

}
